[2024-03-27 16:33:58,744][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=1, round_timeout=None)
[2024-03-27 16:34:14,996][flwr][INFO] - Flower VCE: Ray initialized with resources: {'GPU': 1.0, 'object_store_memory': 2727256473.0, 'CPU': 12.0, 'node:127.0.0.1': 1.0, 'memory': 5454512948.0}
[2024-03-27 16:34:14,999][flwr][INFO] - Initializing global parameters
[2024-03-27 16:34:15,001][flwr][INFO] - Requesting initial parameters from one random client
[2024-03-27 16:34:18,257][flwr][ERROR] - [36mray::launch_and_get_parameters()[39m (pid=14516, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 640, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 644, in ray._raylet.execute_task
  File "c:\Users\ACER\anaconda3\envs\flower_test_1\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 135, in launch_and_get_parameters
    client: Client = _create_client(client_fn, cid)
  File "c:\Users\ACER\anaconda3\envs\flower_test_1\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "d:\HocTap\flower_federated\client.py", line 74, in client_fn
    return FlowerClient(
TypeError: __init__() got an unexpected keyword argument 'valloader'
